apiVersion: apps/v1
kind: Deployment
metadata:
  name: zero-trust-bank
  namespace: default
  labels:
    app: bank-app
spec:
  replicas: 2  # High Availability: If one crashes, the other stays up
  selector:
    matchLabels:
      app: bank-app
  template:
    metadata:
      labels:
        app: bank-app
    spec:
      securityContext:
        runAsUser: 1000        # Zero Trust: Never run as Root
        runAsGroup: 3000
        fsGroup: 2000
      containers:
      - name: bank-app
        image: REPLACE_WITH_ECR_URL:v1
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        # The Health Check: K8s will ping this to make sure the app is alive
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
