name: Deploy Bank Infrastructure

on:
  push:
    branches:
      - main  # Run this whenever we push to main

permissions:
  id-token: write # Required for OIDC (The Trust Handshake)
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    # 1. Download the code from the repo
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Log in to AWS using the "Zero Trust" OIDC Role
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: af-south-1

    # 3. Install Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    # 4. Initialize (Download Plugins)
    - name: Terraform Init
      run: terraform init

    # 5. Apply (Build the Bank)
    - name: Terraform Apply
      run: terraform apply -auto-approve
